# Author: Chitron Bhattacharjee
# Description: Workflow to deploy the ebook project to GitHub Pages

name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main 

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # এখানে শুধু ফোল্ডারের নাম দিতে হবে, ফাইলের নাম নয়
          path: 'বিপ্লব ও ধর্মের সংঘাত প্রসঙ্গে/' 

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
